# Generated by Django 4.2.1 on 2023-09-30 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user/'),
            preserve_default=False,
        ),
    ]
