# Generated by Django 4.2.1 on 2023-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
